### PR TITLE
platform agnostic for file path definition, to fix gulp-wrap-amd/issues/...

### PR DESCRIPTION
**Pull request by mattma**
I have come up with solid solution to unify the platform filepath delimiter. It passes all tests. Do I need to add a test case for it?

### CODE REVIEW

**Comment by phated** [comment]
A test case is needed for this.  I will probably be adding appveyor for windows testing also.

**Comment by phated** [comment]
are you using split and join to avoid the global regex for a `.replace`?

**Comment by mattma** [comment]
First reason, `'templates\\application'.replace('\\', '/')`, I was not sure that it would work as I expect because `\\` look at skip '\' or just double '\'.

Second, using `path.sep` guarantee it would be platform agnostic, window, mac, firefox os, whatever... because node would pick up the platform and fill the value for the variable.  

Third, I do not have a window computer to test it. l blind coded. :)

**Comment by mattma** [comment]
OK. Time to write some tests. :) after I play with new shining `io.js`

**Comment by mattma** [comment]
I am trying to write a test for the feature but I could not come up with a smart solution. 

Here is what I need to test:  ( Testing the `opts.name` )

```js
    opts.name = path.relative(opts.moduleRoot, opts.file.path).slice(0, -path.extname(opts.file.path).length);
    // platform agnostic for file path definition
    opts.name = opts.name.split(path.sep).join('/');
```

This is what I have currently: comment my question inside

```js
test('should have a definition name with "/" separated path', function(t) {
  t.plan(1);

  gulp.src(filename)
    .pipe(task({
      moduleRoot: 'fixtures/',
      modulePrefix: 'rocks',

      // passing the `file.path` won't work, because it is caught inside 
      // `opts.name = path.relative(opts.moduleRoot, opts.file.path).slice(0, -path.extname(opts.file.path).length);`
     // opts.file.path is always the value of what is `fixtures/helloworld` is being read from the disc. 
      // I am using `mac` and do not have windows computer to test
     // How could I simulate or hard code the `opts.file.path` value in the test???

      file: {
        path: 'C:\\Windows\\wrapamd\\fixtures\\template\\helloworld1'
      }
    }))
    .pipe(expectStream(t, {
      name: 'rocks/helloworld1'
    }));
});
```

**Comment by phated** [comment]
I don't think the expectStream pattern will work here, we will have to have a precompiled template with `/` instead of `\\` and then run against windows (appveyor)

**Comment by mattma** [comment]
It sounds like that we could not do anything at this moment to get the test running unless that we have a physical windows machine to test the feature.

What do you want to do this PR? 

Do you think it is safe to merge it and then we roll in the additional tests whenever windows server is ready?

**Comment by phated** [comment]
I will hook up appveyor CI when we have a passing test

**Comment by mattma** [comment]
Sounds good. Thanks. Have a good weekend!

**Comment by phated** [comment]
I wrote the failing test and ran it on appveyor - see https://ci.appveyor.com/project/phated/gulp-wrap-amd/build/2

**Comment by phated** [comment]
Just merged your PR and the test, appveyor is running to make sure it's fixed and the test works.

**Comment by phated** [comment]
Tests passing! https://ci.appveyor.com/project/phated/gulp-wrap-amd/build/3 Thanks!

**Comment by mattma** [comment]
Sweet!

The test's implementation is straight forward and is definitely inspired me to think further. ( well, I did not come out anything yesterday. )

I look at the line [here](https://github.com/phated/gulp-wrap-amd/blob/master/test/test.js#L195). It needs one additional file `./expect/helloworld.js` to read for comparing. 

Here is something similar but one less file to create/read

```js
t.equals(!!~String(file.contents).indexOf("rocks/helloworld"), true);
```

I am going to submit another PR. Take it or leave it, it is totally up to you. 

Current implementation works just fine.

**Pull request merged**
